import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'
import Search from '../components/Search'
import { useState,useEffect } from 'react'
import axios from 'axios'
import DropDown from '../components/DropDown'
import Form from '../components/Form'
import { Navbar } from '../components/Navbar'
import Links from '../components/Links'
export default function Home({socials}) {
  const [searched,setSearched] = useState("");
  const [type,setType] = useState("");
  const [form,openform] =useState("");
  const [filteredResturants,setFilteredResturants] = useState(socials);
  const requestSearch = (searchedVal) => {
    if(searchedVal == ""){
      setFilteredResturants(socials)
    }
      const filter1 = socials.filter((obj) => {
        return obj.displayname.toLowerCase().includes(searchedVal.toLowerCase());
      });
      const filtered = filter1.filter((obj) => {
        return obj.type.toLowerCase().includes(type.toLowerCase());
      });
      setFilteredResturants(filtered);

  };
  useEffect(()=>{
    requestSearch(searched);
},[searched,type])

  return (
    <div className={styles.container}>
      <Head>
        <title>Social Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <div className={styles.searchSection}>
          <div className={styles.searchWrapper}>
            <Search searched={searched} setSearched={setSearched}/>
          </div>
          <div className={styles.dropDownWrapper}>
            <DropDown setType={setType} type={type}/>
          </div>
        </div>
        <div className={styles.grid}>
          <Card socials={filteredResturants}/>
        </div>
        <Links openform={openform}/>
        {form==""?(<></>):(<Form form={form} openform={openform}/>)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ali-yaghi-cv.web.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Ali Yaghi
          </span>
        </a>
      </footer>
    </div>
  )
}
export const getServerSideProps = async () => {
  const res1 = await axios.get(`${process.env.NEXT_PUBLIC_CLIENT_URL}/api/socials`);
  return {
    props: {
      socials: res1.data
    },
  };
}